---
title: "Debate_01"
author: "Marcos Zamora Amengual"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

-----------


### Índice

1. [BIO](#Bio)
    1. [Título](#Titulo)
    2. [Tipo de microarrays](#Tipo)
    3. [Número de muestras](#Numero)
    4. [Pregunta principal](#Pregunta)
    5. [Enlace](#Enlace)
    6. [Comentarios](#Coment)
2. [INFO](#Info)


-----------

# Parte 1 - BIO<a name="Bio"></a>

### Título del estudio:<a name="Titulo"></a>

A genome-wide survey of interaction between rice and Magnaporthe oryzae via microarray analysis 

### Tipo de microarrays:<a name="Tipo"></a>

Para el estudio utilizaron chips para mRNA de 4x44K Oligo Rice Microarray con 42,489 sondas para oligonucleótidos 60-meros.
Se utilizaron 24 microarrays de un solo colorante con 3 réplicas independientes para cada uno de los grupos del experimento

### Número de muestras y grupos:<a name="Numero"></a>

<p style="text-align: justify">El estudio se realizó con 16 muestras de hojas obtenidas de plantas de arroz crecidas en el laboratorio a partir de semillas de Oryza sativa Nipponbare de la cepa 007.
Estas muestras se dividieron en 3 grupos dependiendo de el momento de infección de la planta con Magnaporthe oryzae; a las 24, 48 y 72 horas tras la inoculación del hongo en la planta</p>

### Pregunta principal:<a name="Pregunta"></a>

Estudiar si hay respuesta en la expresión génica frente a la infección por Magnaporthe oryzae y en caso de que la haya que genes son los que modifican su expresión

### Enlace:<a name="Enlace"></a>

https://doi.org/10.1080/21655979.2020.1860479

### Comentarios:<a name="Coment"></a>

<p style="text-align: justify">Lo que me parece interesante de este estudio aparte de su relevancia social, ya que el arroz es una fuente de alimento vital para muchas comunidades humanas, es el hecho de que los 3 grupos del estudio son muy claros y que los resultados obtenidos muestran muy bien las diferencias entre ellos, lo que sirve de ejemplo, muy visual y claro, de lo que es un estudio con microarrays del tipo “class comparison”</p>

# Parte 2 - INFO<a name="Info"></a>

